#!/bin/bash

# create_script
# This script created a new bash script, sets permissions and more
# Aithor: slisandr

# Is there an argument?
if [[ ! $1 ]]; then
	echo "Missing argument" >&2
	exit 1
fi
declare open_editor=""
if [[ $# -eq 1 ]]; then
	open_editor="true"
fi

declare -r bindir="${HOME}/bin"

# Check if bin directory exists
if [[ ! -d $bindir ]]; then
	# if not: create bin directory
	if mkdir "$bindir"; then
		echo "Created ${bindir}"
	else
		echo "Could not create ${bindir}"
		exit 1
	fi
fi

while [[ $1 ]]; do
	scriptname="$1"
	filename="${bindir}/${scriptname}"

	if [[ -e $filename ]]; then
		echo "File ${filename} already exists" >&2
		shift
		continue
	fi

	if type "$scriptname" > /dev/null 2>&1; then
		echo "There is already a command with name ${scriptname}" >&2
		shift
		continue
	fi

	# Create a script with some lines:
	echo '#!/bin/bash' > "$filename"
	echo '' >> "$filename"
	echo '# Author: slisandr' >> "$filename"
	echo '# Description:' >> "$filename"

	# Add executable permission
	chmod u+x "$filename"

	shift
done


# Open with editor
if [[ $open_editor ]]; then
	echo "Opening"
	if [[ $EDITOR ]]; then
		$EDITOR "$filename"
	else
		echo "Script created; not starting editor because \$EDITOR is not set"
	fi
fi

exit 0
