#!/bin/bash

# Description: change filename extensions
# Author: slisandr

if [[ $# -ne 2 ]]; then
	echo "Need exactly two arguments"
fi

for f in *"$1"; do
	base=$(basename "$f" "$1")
	mv "$f" "${base}$2"
done
